# Generated by Django 5.2 on 2025-07-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admissionapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='submitted_at',
            new_name='applied_on',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='class_applying_to',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
